"""empty message

Revision ID: 173379ea1417
Revises: c1af8a2f100b
Create Date: 2022-05-27 16:57:51.711142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173379ea1417'
down_revision = 'c1af8a2f100b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artist', 'seeking_venue')
    # ### end Alembic commands ###
