"""empty message

Revision ID: 189be8997d92
Revises: 9709e33854a7
Create Date: 2022-05-28 07:30:50.576379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189be8997d92'
down_revision = '9709e33854a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('start_time', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('show', 'start_time')
    # ### end Alembic commands ###
