"""empty message

Revision ID: 89bc448c10be
Revises: 5ba4d74279b7
Create Date: 2022-05-27 16:17:53.538597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bc448c10be'
down_revision = '5ba4d74279b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('artist', 'require_talent')
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.drop_column('venue', 'require_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('require_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venue', 'seeking_talent')
    op.add_column('artist', sa.Column('require_talent', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artist', 'seeking_talent')
    # ### end Alembic commands ###
