"""empty message

Revision ID: 8b184ecf8915
Revises: 173379ea1417
Create Date: 2022-05-27 23:19:18.972983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b184ecf8915'
down_revision = '173379ea1417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('table', sa.Column('venue_id', sa.Integer(), nullable=False))
    op.add_column('table', sa.Column('start_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'start_time')
    op.drop_column('table', 'venue_id')
    op.drop_column('table', 'artist_id')
    # ### end Alembic commands ###
